# Generated by Django 3.0.5 on 2020-05-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('stock', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('policy', models.TextField(blank=True, null=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('isUpComing', models.BooleanField(blank=True, default=False, null=True)),
                ('isFeatured', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Category')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.SubCategory')),
            ],
        ),
    ]
