# Generated by Django 3.0.5 on 2020-05-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transactionId',
            field=models.CharField(default='1588472997259662', max_length=100),
        ),
    ]
