# Generated by Django 3.0.5 on 2020-05-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200503_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transactionId',
            field=models.CharField(default='1588473177344291', max_length=100, unique=True),
        ),
    ]
