# Generated by Django 3.0.5 on 2020-05-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200503_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transactionId',
            field=models.CharField(default='1588622267025868', max_length=100),
        ),
    ]
