# Generated by Django 3.0.5 on 2020-05-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200505_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transactionId',
            field=models.CharField(default='1588623291639308', max_length=100, unique=True),
        ),
    ]
